name: "Test"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix build .#checks.x86_64-linux.formatting

  build-cache:
    strategy:
      matrix:
        package: [pkgs-all-cross, pkgs-all-native]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          enable_kvm: true
          extra_nix_config: |
            substituters = https://cache.nixos.org https://cache.nichi.co https://cache.ztier.in
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.nichi.co-0:P3nkYHhmcLR3eNJgOAnHDjmQLkfqheGyhZ6GLrUVHwk= cache.ztier.link-1:3P5j2ZB9dNgFFFVkCQWT3mh0E+S3rIWtZvoql64UaXM=
            system-features = nixos-test benchmark big-parallel kvm
            extra-platforms = riscv64-linux

      - name: Setup Attic cache
        uses: ryanccn/attic-action@v0
        with:
          endpoint: ${{ secrets.ATTIC_ENDPOINT }}
          cache: ${{ secrets.ATTIC_CACHE }}
          token: ${{ secrets.ATTIC_TOKEN }}

      - name: "Build Packages"
        run: nix build ".#${{ matrix.package }}"
